name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master # Triggers on either main or master
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Uses the latest stable Go version

      - name: Compile Go to WebAssembly
        run: |
          # Build the WebAssembly binary
          GOOS=js GOARCH=wasm go build -o ./static/main.wasm ./cmd/wasm

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './static' # Only uploads the static frontend directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
